### PR TITLE
New blood

### PR DESCRIPTION
**Pull request by Dragonoidzero**
So uh, hi! I am a pretty big fan of Haema and vampire mods in general, and I was in a spriting mood recently so I decided to give retexturing the blood bar textures a hand. I think they came out nicely so if you want you can have them. I am also interested in remaking the textures for the whole mod if you would want that.

[Ps: This is how the new blood looks ingame.](https://imgur.com/nNPLSJa)

### CODE REVIEW

**Comment by williambl** [comment]
Wow, that looks awesome! Thank you so much. Would you mind if I replaced the blood droplets in the mod logo with your ones, too?

**Comment by Dragonoidzero** [comment]
Feel free, although I could make a new logo altogether if you are interested

**Comment by Dragonoidzero** [comment]
[Reworked some more textures](https://media.discordapp.net/attachments/523251999899385875/804267738507378728/unknown.png)

Logo is in the sights :eye: :eye: may paint something for it idk :tater:.

**Comment by williambl** [comment]
Those look awesome! Thank you so much.

**Comment by Dragonoidzero** [comment]
Texture rework is complete, the pr is ready when you are

**Comment by williambl** [comment]
Just had a little playtest with the new textures - they look really good in game! I'll add you to the CF project once I upload a release with these textures :)

**Pull request merged**
